overrides:
  ceph-deploy:
    conf:
      global:
        debug ms: 1
      osd:
        debug osd: 10
      mon:
        debug mon: 10
roles:
- - mon.a
  - mds.0
  - osd.0
- - osd.1
  - mon.b
  - client.0
tasks:
- install:
     extras: yes
- print: "**** done install extras"
- ssh_keys:
- print: "**** done ssh_keys"
- ceph-deploy:
- print: "**** done ceph-deploy"
- ceph-fuse:
- print: "**** done ceph-fuse"
- workunit:
     clients:
        client.0:
           - suites/blogbench.sh
- print: "**** done suites/blogbench.sh"
exclude_arch: armv7l
