roles:
- - mon.a
  - mds.0
  - osd.0
- - mon.b
  - osd.1
- - client.0
tasks:
- install:
     extras: yes
- ssh_keys:
- ceph-deploy:
- workunit:
     clients:
        client.0:
           - rbd/run_cli_tests.sh
