#cloud-config-archive

- type: text/cloud-config
  content: |
    output:
      all: '| tee -a /var/log/cloud-init-output.log'

# allow passwordless access for debugging
- |
  #!/bin/bash
  exec passwd -d ubuntu

- |
  #!/bin/bash

  # mount a 9p fs for storing logs
  mkdir /mnt/log
  mount -t 9p -o trans=virtio test_log /mnt/log

  # mount the iso image that has the test script
  mkdir /mnt/cdrom
  mount -t auto /dev/cdrom /mnt/cdrom
