overrides:
  ceph:
    conf:
      global:
        ms die on skipped message: false
tasks:
- ansible:
- install:
- ceph:
    fs: xfs
- kclient:
- workunit:
    clients:
      all:
        - suites/fsstress.sh
