overrides:
  ceph:
    conf:
      global:
        ms die on skipped message: false
tasks:
- ansible:
- install:
- ceph:
    fs: btrfs
- rbd:
    all:
      image_size: 20480
- workunit:
    tag: v0.94.1
    clients:
      all:
        - suites/iozone.sh
