tasks:
- install:
    extra_packages: ['ceph-selinux']
- ceph:
    fs: btrfs
- ceph-fuse:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd_python.sh
    env:
      RBD_FEATURES: "1"
