overrides:
  ceph-deploy:
    conf:
      global:
        debug ms: 1
      osd:
        debug osd: 10
      mon:
        debug mon: 10
roles:
- - mon.a
  - mds.0
  - osd.0
  - osd.1
  - osd.2
- - mon.b
  - osd.3
  - osd.4
  - osd.5
- - mon.c
  - osd.6
  - osd.7
  - osd.8
- - client.0
openstack:
  - machine:
     disk: 40 # GB
     ram: 8000 # MB
     cpus: 1
    volumes: # attached to each instance
     count: 3
     size: 10 # GB
tasks:
- install:
     extras: yes
- ssh_keys:
- ceph-deploy:
- workunit:
     clients:
        all:
           - rados/load-gen-big.sh

