overrides:
   ansible:
    repo: https://github.com/ceph/ceph-cm-ansible.git
    playbook: downstream_setup.yml
    cleanup: true
    vars:
      yum_repos:
         - url: "http://fpaste.org/244005/43682819/raw/"
           name: "all_repo"
      disable_yum_repos: ['epel', 'rhel7', 'rhel7-optional', 'rhel7-extras', 'lab-extras', 'rhel-7-fcgi-ceph'] 
   install:
    ceph: 
     rhbuild: 1.3.0
     log-whitelist: ['slow request', 'slow requests' ]
    conf:
      client:
        rbd cache: true
      global:
        ms inject socket failures: 5000
tasks:
- ansible: null
- install: null
- ceph:
    fs: xfs
- thrashosds:
    timeout: 1200
- rbd_fsx:
    clients:
    - client.0
    ops: 2000
