overrides:
  ceph:
    log-whitelist:
    - reached quota
    - wrongly marked me down
tasks:
- install:
- ceph:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

openstack:
  machine:
    disk: 40 # GB
    ram: 8000 # MB
    cpus: 1
  volumes: # attached to each instance
    count: 0
    size: 1 # GB
